apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- stateful-set.yaml
images:
- name: gcr.docker.prod.walmart.com/$(project)/application-controller
  newName: gcr.docker.prod.walmart.com/$(project)/application-controller
  newTag: latest
