apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cert.yaml
- config-map.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- secret.yaml
- statefulset.yaml
- service.yaml
- webhook.yaml
commonLabels:
  kustomize.component: kfserving
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- envs:
  - params.env
  name: kfserving-config
vars:
- name: registry
  objref:
    kind: ConfigMap
    name: kfserving-config
    apiVersion: v1
  fieldref:
    fieldpath: data.registry
configurations:
- params.yaml
images:
- name: gcr.docker.prod.walmart.com/kubebuilder/kube-rbac-proxy
  newName: gcr.docker.prod.walmart.com/kubebuilder/kube-rbac-proxy
  newTag: v0.4.0
- name: gcr.docker.prod.walmart.com/kfserving/kfserving-controller
  newName: gcr.docker.prod.walmart.com/kfserving/kfserving-controller
  newTag: v0.3.0
