apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.docker.prod.walmart.com/ml-pipeline/persistenceagent
        imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-persistenceagent
