apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemon-set.yaml
commonLabels:
  kustomize.component: gpu-driver
images:
- name: gcr.docker.prod.walmart.com/google-containers/pause
  newName: gcr.docker.prod.walmart.com/google-containers/pause
  newTag: '2.0'
- name: cos-nvidia-installer
  newName: cos-nvidia-installer
  newTag: fixed
