apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxnet-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mxnet-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - command:
        - /opt/hub.docker.prod.walmart.com/kubeflow/mxnet-operator.v1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: hub.docker.prod.walmart.com/mxjob/mxnet-operator:v1beta1
        imagePullPolicy: Always
        name: mxnet-operator
      serviceAccountName: mxnet-operator
